//
//  Pokemon.swift
//  pokedex-bootcamp
//
//  Created by Aylwing Olivas on 4/14/23.
//

import UIKit

struct Pokemon {
    
    let name: String
    let type: String
    let pokemonnumber: Int
    let biology: String
    let photo: UIImage
}

let pokemons: [Pokemon] = [
    Pokemon(name: "Bulbasaur", type: "Grass", pokemonnumber: 0001, biology: "Bulbasaur es un Pokémon cuadrúpedo de color verde, posee manchas de una tonalidad más oscura del mismo color con distintas formas geométricas", photo: UIImage(named:"Bulbasaur")!),
    Pokemon(name: "Ivysaur", type: "Grass", pokemonnumber: 0002, biology: "Ivysaur posee una tonalidad azulada más viva que la de su preevolución, Bulbasaur. Además, sus ojos se mantienen rojos y sus pupilas negras. El bulbo que había en la espalda de Bulbasaur ha brotado mostrando un botón de flor, la cual aún permanece cerrada", photo: UIImage(named: "Ivysaur")!),
    Pokemon(name: "Venusaur", type: "Grass", pokemonnumber: 0003, biology: "Venusaur esta basado en una rana, al igual que toda su línea evolutiva. El botón de flor que lleva sobre su lomo se abre completamente, dejando ver una enorme flor rosada, parecida a Rafflesia arnoldii y unas hojas semejantes a las o de una cicadacea", photo: UIImage(named: "Venusaur")!),
    Pokemon(name: "Charmander", type: "Fire", pokemonnumber: 0004, biology: "Charmander es un pequeño lagarto bípedo. Sus características de fuego son resaltadas por su color de piel anaranjado y su cola, cuya punta está envuelta en llamas. Charmander y sus evoluciones, Charmeleon y Charizard, tienen una pequeña llama en la punta de sus colas desde que nacen", photo: UIImage(named:"Charmander")!),
    Pokemon(name: "Charmeleon", type: "Fire", pokemonnumber: 0005, biology: "Charmeleon es un gran lagarto bípedo con escamas de color rojo oscuro y en la parte inferior de color crema (desde el pecho hasta abajo), posee como característica general una llama en la punta de su cola al igual que Charmander y Charizard", photo: UIImage(named: "Charmeleon")!),
    Pokemon(name: "Charizard", type: "Fire", pokemonnumber: 0006, biology: "La figura de Charizard es la de un dragón erguido sobre sus dos patas traseras, que sostienen su peso. Posee unas poderosas alas y un abrasador aliento de fuego. También posee un cuello largo y una poderosa cola terminada en una llama que arde con más fuerza si ha vivido duros combates", photo: UIImage(named: "Charizard")!),
    Pokemon(name: "Squirtle", type: "Water", pokemonnumber: 0007, biology: "Squirtle tiene forma de una tortuga semiacuática de una tonalidad azulada, su caparazón es color café, las placas periféricas de color blanco y finalmente su plastrón de una tonalidad crema, posee una cola con la punta enrollada, además de tres dedos en cada una de sus extremidades", photo: UIImage(named:"Squirtle")!),
    Pokemon(name: "Wartortle", type: "Water", pokemonnumber: 0008, biology: "Wartortle es una tortuga semiacuática de una tonalidad azulada más oscura que Squirtle, su cola ha crecido bastante y ha cambiado de color hacia un azul muy claro finalizando en varias puntas enrolladas", photo: UIImage(named: "Wartortle")!),
    Pokemon(name: "Blastoise", type: "Water", pokemonnumber: 0009, biology: "Blastoise está basado en una tortuga con dos cañones. Es una enorme tortuga bípeda, que puede extender unos poderosos cañones situados en su espalda para disparar potentes chorros de agua, con la fuerza suficiente para quebrar muros de hormigón o hacer agujeros en planchas de acero", photo: UIImage(named: "Blastoise")!),
    Pokemon(name: "Caterpie", type: "Bug", pokemonnumber: 0010, biology: "Caterpie podría estar basado en una oruga del género Papilio, orugas con un diseño que imita grandes ojos como los de Caterpie y un par de apéndices sobre la cabeza muy similares a las antenas de Caterpie", photo: UIImage(named:"Caterpie")!),
    Pokemon(name: "Metapod", type: "Bug", pokemonnumber: 0011, biology: "Está basado en la crisálida de una Papilio. Su piel es de color verde intenso, en la que solamente sus ojos son visibles. Su boca es el pequeño rombo que tiene un poco debajo de la altura de sus ojos, por donde puede disparar su disparo demora", photo: UIImage(named: "Metapod")!),
    Pokemon(name: "Butterfree", type: "Bug", pokemonnumber: 0012, biology: "Butterfree está basado en una mariposa y su forma Gigamax en mothra. Su cuerpo está dividido en dos partes: cabeza y tronco. Butterfree posee unos grandes ojos rojos, un cuerpo de color púrpura oscuro, dos pequeñas manos y dos pies de un color azul cielo", photo: UIImage(named: "Butterfree")!),
    Pokemon(name: "Weedle", type: "Bug", pokemonnumber: 0013, biology: "Este Pokémon insecto tiene la forma de un gusano con un cuerno que segrega veneno en la punta de su aguijón de 5 cm que tiene en la frente, que puede utilizar para defenderse de sus depredadores. Por ello, y por el color de su cuerpo, hace que muchos Pokémon eviten confrontarse con él", photo: UIImage(named:"Weedle")!),
    Pokemon(name: "Kakuna", type: "Bug", pokemonnumber: 0014, biology: "Kakuna está basado en una pupa de avispa. Es una especie de capullo muy duro, de color amarillo, con dos enormes ojos de color negro con forma triangular, tiene dos brazos en forma de guadaña en el medio de su cuerpo", photo: UIImage(named: "Kakuna")!),
    Pokemon(name: "Beedrill", type: "Bug", pokemonnumber: 0015, biology: "Beedrill está basado en una avispa japonesa, comparte muchas características con las avispas y abejas, de forma que también es parecido a Combee y Vespiquen. Es bastante territorial, si su colmena es molestada o invadida comenzarán a atacar en un furioso enjambre", photo: UIImage(named: "Beedrill")!),
    Pokemon(name: "Pidgey", type: "Flying", pokemonnumber: 0016, biology: "Pidgey es un ave Pokémon de color marrón y crema, y con un pequeño pico y patas fuertes. Su aspecto y colores se asemejan al de un ampelis americano, también recuerda al gorrión molinero", photo: UIImage(named:"Pidgey")!),
    Pokemon(name: "Pidgeotto", type: "Flying", pokemonnumber: 0017, biology: "Los Pidgeotto son aves grandes, quizá basadas en aves de presa y pescadoras, con garras afiladas, una cola de plumas rojas y amarillas, así como una cresta roja en su cabeza", photo: UIImage(named: "Pidgeotto")!),
    Pokemon(name: "Pidgeot", type: "Flying", pokemonnumber: 0018, biology: "Los Pidgeot se asemejan a sus preevoluciones, aunque siendo de mayor tamaño y con un penacho de plumas sumamente largo y su cola con un tono rojizo uniforme", photo: UIImage(named: "Pidgeot")!),
    Pokemon(name: "Rattata", type: "Normal", pokemonnumber: 0019, biology: "Rattata es un Pokémon con forma de ratón, de una tonalidad púrpura con el vientre de color crema. Tiene dos grandes dientes incisivos y unos largos bigotes en las mejillas", photo: UIImage(named:"Rattata")!),
    Pokemon(name: "Raticate", type: "Normal", pokemonnumber: 0020, biology: "Raticate se asemeja a una rata noruega o rata marrón. Tiene la piel marrón claro y una larga cola. Sus colmillos son grandes, duros y firmes, y le permiten roer cualquier cosa", photo: UIImage(named: "Raticate")!),
    Pokemon(name: "Spearow", type: "Flying", pokemonnumber: 0021, biology: "Spearow tiene una forma parecida a la de un gorrión castaño. Tiene muchas tonalidades en su plumaje, siendo marrón en la cabeza y cola, negro en el lomo, crema en el vientre y rojizo en las alas, con las puntas de estas un poco más claras", photo: UIImage(named: "Spearow")!),
    Pokemon(name: "Fearow", type: "Flying", pokemonnumber: 0022, biology: "Este Pokémon, con forma de una gran ave, tiene una tonalidad marrón con plumas más claras en la punta de sus alas y en su espalda. Tiene un cuello y picos largos y delgados", photo: UIImage(named: "Fearow")!),
    Pokemon(name: "Ekans", type: "Poison", pokemonnumber: 0023, biology: "Este Pokémon esta basado en una serpiente, por su apariencia se asemeja a una serpiente de cascabel, sin embargo Ekans no es venenoso. De tonalidad púrpura tiene un cascabel en la cola, un anillo en el cuello y un vientre de color amarillo", photo: UIImage(named:"Ekans")!),
    Pokemon(name: "Arbok", type: "Poison", pokemonnumber: 0024, biology: "Arbok parece estar inspirado en la cobra de anteojos. De color púrpura en todo su cuerpo, posee una capucha que, a diferencia de una cobra real, no se puede retraer. Su cuerpo parece segmentado con varias líneas de una tonalidad más oscura", photo: UIImage(named: "Arbok")!),
    Pokemon(name: "Pikachu", type: "Electric", pokemonnumber: 0025, biology: "Pikachu es un pequeño Pokémon cuya morfología se encuentra basada en un roedor. Aunque su nombre y su categoría hagan alusión a un ratón, según su diseñadora, sus mejillas están basadas en una ardilla", photo: UIImage(named:"Pikachu")!),
    Pokemon(name: "Raichu", type: "Electric", pokemonnumber: 0026, biology: "Este Pokémon es un gran roedor bípedo. Tiene un pelaje anaranjado, una cola oscura y gruesa como un cable de tendido eléctrico que termina en forma de rayo y totalmente plana, que además puede soportar grandes cargas", photo: UIImage(named: "Raichu")!),
    Pokemon(name: "Sandshrew", type: "Ground", pokemonnumber: 0027, biology: "Pese a su nombre, la apariencia de Sandshrew es más semejante a la de un armadillo o un pangolín que a la de una musaraña. Es una criatura pequeña, amarilla y de apariencia similar a un armadillo cubierto de placas duras y con garras afiladas", photo: UIImage(named:"Sandshrew")!),
    Pokemon(name: "Sandslash", type: "Ground", pokemonnumber: 0028, biology: "Sandslash habita en las mismas zonas áridas que su preevolución Sandshrew, en madrigueras. A veces se les puede ver trepando árboles con sus garras por varias razones, ya sea para dormir en su follaje, cortar y dejar caer bayas para los Sandshrew que esperan debajo o usarlos como escondite de caza", photo: UIImage(named: "Sandslash")!),
    Pokemon(name: "Nidoran♀", type: "Poison", pokemonnumber: 0029, biology: "Al igual que el macho, oculta en sus púas un poderoso veneno, están pensadas como protección para su pequeño cuerpo. Cuando se enfurece libera una horrible toxina de sus cuernos", photo: UIImage(named:"Nidoran♀")!),
    Pokemon(name: "Nidorina", type: "Poison", pokemonnumber: 0030, biology: "De un tamaño muy similar a Nidorino, es de tonalidad azulada y a diferencia del antes mencionado carece de un cuerno en su cabeza que según parece se ha atrofiado para evitar herir a sus crías", photo: UIImage(named: "Nidorina")!),
    Pokemon(name: "Nidoqueen", type: "Poison", pokemonnumber: 0031, biology: "Este Pokémon bípedo posee escamas de tonalidad azulada, además de dos placas en el pecho de color amarillo, al igual que en la parte inferior del abdomen y en la parte inferior de su mandíbula", photo: UIImage(named: "Nidoqueen")!),
    Pokemon(name: "Vulpix", type: "Fire", pokemonnumber: 0037, biology: "Vulpix está basado en un zorro rojo, y un kitsune. Es un Pokémon de tamaño pequeño y de patas cortas. Su suave pelaje es corto excepto en el flequillo y en sus seis colas", photo: UIImage(named:"Vulpix")!),
    Pokemon(name: "Ninetales", type: "Fire", pokemonnumber: 0038, biology: "Su pelaje es de color dorado, el cual se va haciendo más intenso a medida que envejece y las puntas de sus colas de un color amarillo mostaza o naranja, que al paso de los años va cambiando de color", photo: UIImage(named: "Ninetales")!),
    Pokemon(name: "Ponyta", type: "Fire", pokemonnumber: 0077, biology: "Al nacer es un poco débil y lento, pero a los pocos minutos se hacen tan fuertes que pueden cargar a una persona adulta sin mucho esfuerzo, además de ser lo suficientemente rápido para seguir a su padres", photo: UIImage(named: "Ponyta")!),
    Pokemon(name: "Rapidash", type: "Fire", pokemonnumber: 0078, biology: "Es más alto que los Ponyta, pues su fisonomia se asemeja más a un caballo, su crin de llamas es más grande y posee un cuerno en la frente", photo: UIImage(named:"Rapidash")!),
    Pokemon(name: "Articuno", type: "Ice", pokemonnumber: 0144, biology: "Articuno es un enorme pájaro de color azulado, con una cresta en forma de tres rombos más oscura en la cabeza, que a su vez tienen la forma de unos carámbanos, del mismo color que su larga cola en forma de cinta brillante", photo: UIImage(named:"Articuno")!),
]
